version: '3' # version of docker-compose

services:
  ur3_task: 
    image: ur3_v2:latest
    container_name: ur3_container
    network_mode: host
    privileged: true
#    user: root
    volumes:
      # ---------------------------------------------------------------------
      # Remember that to allow docker to public GUI tools on your computer
      # you have to run "xhost +local:root". To disallow, "xhost -local:root"
      #
      # The volume below allows the container to have access to the
      # "physical display". If the DISPLAY variable is :0, then the graphical
      # things will be written at /tmp/.X11-unix/X0
      # ---------------------------------------------------------------------
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/Projects/ur3-foxy/ros2_ws/src:/ros2_ws/src:rw
    environment: # set ENV vars
      - DISPLAY # Forward the DISPLAY variable of the host to the container
      - QT_X11_NO_MITSHM=1 # Taken from https://answers.ros.org/question/391195/using-rviz-in-docker/?answer=391504#post-id-391504
      - TURTLEBOT3_MODEL=burger

    # entrypoint: ["/bin/bash", "-c"]
    command:
      - bash
      - -c
      - | 
        cd ros2_ws && \
        terminator -u --title="Docker Container" 



       